version: "3.3"

services:
  web:
    build: .
    environment:
      - SECRET_KEY=${SECRET_KEY}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000